version: '3.8'

services:
  webapp:
    build:
      context: ./FoodHelper
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      FoodContext: "Server=db;Database=FoodHelperDb;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;"

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
