version: '3.8'

services:
  webapp:
    build: ./food-helper
    ports:
      - "443:443"  # Pas de poort aan indien nodig, bijvoorbeeld als je HTTPS gebruikt
    depends_on:
      - db
     environment:
      - ConnectionString=Server=db;Database=FoodHelperDb;User=sa;Password=yourStrong(!)Password;

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
